### ISSUE TITLE
Pretraga

### ISSUE THREAD

**Issue by Doktor-X** [nirvana-7777/plugin.video.hrti#12]
Pozdrav, plugin radi bez većih problema, no jedan od većih nedostataka (bar po meni) je da fali pretraga.

**Comment by nirvana-7777** [comment]
There are some issues here.
1) I don't speak Croatian. This might come as a surprise but at least I would prefer if you could write in English.
2) This is about issues. If I get you right this is more about a feature request. If so please come and discuss in the forum.

Best  regards
