### ISSUE TITLE
Ne radi na Linuxu

### ISSUE THREAD

**Issue by muzena** [nirvana-7777/plugin.video.hrti#4]
@nirvana-7777 
Upišem korisničko ime i lozinku, probam pokrenuti HRTi i jednostavno prikaže poruku greške.
OS je Linux Mint 20.3
[kodi.log](https://github.com/nirvana-7777/plugin.video.hrti/files/7997480/kodi.log)

**Comment by nirvana-7777** [comment]
Kodi six is not installed: https://kodi.wiki/view/Add-on:Kodi_Six

**Comment by muzena** [comment]
It worked after installing dependencies addons.
